mkdev_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.flatpages import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap, NewsSitemap, ArticlesSitemap
from newsfeed.urls import *
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from rest_framework.routers import DefaultRouter
from newsfeed import views


sitemaps = {
    'static': StaticViewSitemap,
    'flatpages': FlatPageSitemap,
    'news': NewsSitemap,
    'articles': ArticlesSitemap,
}

router = DefaultRouter()
router.register('api/newsfeed', views.NewsViewSet)
router.register('api/articles', views.ArticlesViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('newsfeed.urls', namespace='newsfeed')),
    path('', TemplateView.as_view(template_name="main_page.html")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('', include(router.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

urlpatterns += path('', include('django.contrib.flatpages.urls')),  # в конце, потому что любит перехватывать ссылки

newsfeed/urls.py
from django.urls import path, re_path
from newsfeed.views import *

app_name = 'newsfeed'

urlpatterns = [
    path(r'newsfeed/<slug:slug>/', NewsPostDetailView.as_view(), name='news-detail'),
    path(r'newsfeed/', NewsPostListView.as_view(), name='news-list'),
    path(r'articles/<slug:slug>/', ArticleDetailView.as_view(), name='article-detail'),
    path(r'articles/', ArticleListView.as_view(), name='article-list'),
    path(r'search/', SearchListView.as_view(), name='search'),
    path(r'archive/', zip_archive, name='archive-csv'),
]

templates/mobile/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
        {% include 'meta/meta.html' %}
        {% block meta %}{% endblock %}
        <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:700%7CNunito:300,600" rel="stylesheet">
		<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css'  %}">
		<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>

        <title>Название сайта</title>
    </head>
        <body>
<!-- Header -->
		<header id="header">
			<!-- Nav -->
			<div id="nav">
				<!-- Main Nav -->
				<div id="nav-fixed">
					<div class="container">
						<!-- logo -->
						<div class="nav-logo">
							<a href="/" class="logo"><img src="{% static './img/logo.png' %}" alt=""></a>
						</div>
						<!-- /logo -->

						<!-- nav -->
            {% load flatpages %}
            {% get_flatpages as flatpages %}
						<ul class="nav-menu nav navbar-nav">
              {% for page in flatpages %}
              <li><a href="{{ page.url }}">{{ page.title }}</a></li>
              {% endfor %}
							<li><a href="{% url 'newsfeed:news-list' %}">Новости</a></li>
                            <li><a href="{% url 'newsfeed:article-list' %}">Статьи</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'profile' %}">Привет, {{ user.username }}!</a></li>
                            <li><a href="{% url 'logout' %}">Выйти</a></li>
                        {% else %}
                            <li><a href="{% url 'login' %}">Войти</a></li>
                            <li><a href="{% url 'signup' %}">Регистрация</a></li>
                        {% endif %}


						</ul>
						<!-- /nav -->

						<!-- search & aside toggle -->
						<div class="nav-btns">
							<button class="aside-btn"><i class="fa fa-bars"></i></button>
							<button class="search-btn"><i class="fa fa-search"></i></button>
							<div class="search-form">
								<input class="search-input" type="text" name="search" placeholder="Enter Your Search ...">
								<button class="search-close"><i class="fa fa-times"></i></button>
							</div>
						</div>
						<!-- /search & aside toggle -->
					</div>
				</div>
				<!-- /Main Nav -->

				<!-- Aside Nav -->
				<div id="nav-aside">
					<!-- nav -->
					<div class="section-row">
						<ul class="nav-aside-menu">
							<li><a href="/">Главная</a></li>
							<li><a href="/about/">О сайте</a></li>
							<li><a href="/contact/">Контакты</a></li>
							<li><a href="/newsfeed/">Новости</a></li>
							<li><a href="/articles/">Статьи</a></li>
						</ul>
					</div>
					<!-- /nav -->

					<!-- widget posts -->
					<div class="section-row">
						<h3>Recent Posts</h3>
						<div class="post post-widget">
							<a class="post-img" href="{% url 'newsfeed:news-list' %}"><img src="{% static './img/widget-2.jpg' %}" alt=""></a>
							<div class="post-body">
								<h3 class="post-title"><a href="{% url 'newsfeed:news-list' %}">Pagedraw UI Builder Turns Your Website Design Mockup Into Code Automatically</a></h3>
							</div>
						</div>

						<div class="post post-widget">
							<a class="post-img" href="{% url 'newsfeed:news-list' %}"><img src="{% static './img/widget-3.jpg' %}" alt=""></a>
							<div class="post-body">
								<h3 class="post-title"><a href="{% url 'newsfeed:news-list' %}">Why Node.js Is The Coolest Kid On The Backend Development Block!</a></h3>
							</div>
						</div>

						<div class="post post-widget">
							<a class="post-img" href="{% url 'newsfeed:news-list' %}"><img src="{% static './img/widget-4.jpg' %}" alt=""></a>
							<div class="post-body">
								<h3 class="post-title"><a href="{% url 'newsfeed:news-list' %}">Tell-A-Tool: Guide To Web Design And Development Tools</a></h3>
							</div>
						</div>
					</div>
					<!-- /widget posts -->

					<!-- social links -->
					<div class="section-row">
						<h3>Follow us</h3>
						<ul class="nav-aside-social">
							<li><a href="{% url 'newsfeed:news-list' %}"><i class="fa fa-facebook"></i></a></li>
							<li><a href="{% url 'newsfeed:news-list' %}"><i class="fa fa-twitter"></i></a></li>
							<li><a href="{% url 'newsfeed:news-list' %}"><i class="fa fa-google-plus"></i></a></li>
							<li><a href="{% url 'newsfeed:news-list' %}"><i class="fa fa-pinterest"></i></a></li>
						</ul>
					</div>
					<!-- /social links -->

					<!-- aside nav close -->
					<button class="nav-aside-close"><i class="fa fa-times"></i></button>
					<!-- /aside nav close -->
				</div>
				<!-- Aside Nav -->
			</div>
			<!-- /Nav -->
		</header>
		<!-- /Header -->

		<!-- section -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<!-- Post content -->
					<div class="col-md-8">
						<div class="section-row sticky-container">


		{% block content %}
        {% endblock %}

                        			</div>
						</div>

				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /section -->



		<!-- Footer -->
		<footer id="footer">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-5">
						<div class="footer-widget">
							<div class="footer-logo">
								<a href="index.html" class="logo"><img src="{%  static './img/logo.png' %}" alt=""></a>
							</div>
							<ul class="footer-nav">
								<li><a href="{% url 'newsfeed:news-list' %}">Privacy Policy</a></li>
								<li><a href="{% url 'newsfeed:news-list' %}">Advertisement</a></li>
							</ul>
							<div class="footer-copyright">
								<span>&copy; <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></span>
							</div>
						</div>
					</div>

					<div class="col-md-4">
						<div class="row">
							<div class="col-md-6">
								<div class="footer-widget">
									<h3 class="footer-title">О нас</h3>
									<ul class="footer-links">
										<li><a href="{% url 'newsfeed:news-list' %}">О сайте</a></li>
										<li><a href="{% url 'newsfeed:news-list' %}">Join Us</a></li>
										<li><a href="{% url 'newsfeed:news-list' %}">Контакты</a></li>
									</ul>
								</div>
							</div>
							<div class="col-md-6">
								<div class="footer-widget">
									<h3 class="footer-title">Catagories</h3>
									<ul class="footer-links">
										<li><a href="{% url 'newsfeed:news-list' %}">Web Design</a></li>
										<li><a href="{% url 'newsfeed:news-list' %}">JavaScript</a></li>
										<li><a href="{% url 'newsfeed:news-list' %}">Css</a></li>
										<li><a href="{% url 'newsfeed:news-list' %}">Jquery</a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>

					<div class="col-md-3">
						<div class="footer-widget">
							<h3 class="footer-title">Join our Newsletter</h3>
							<div class="footer-newsletter">
								<form>
									<input class="input" type="email" name="newsletter" placeholder="Enter your email">
									<button class="newsletter-btn"><i class="fa fa-paper-plane"></i></button>
								</form>
							</div>
							<ul class="footer-social">
								<li><a href="{% url 'newsfeed:news-list' %}"><i class="fa fa-facebook"></i></a></li>
								<li><a href="{% url 'newsfeed:news-list' %}"><i class="fa fa-twitter"></i></a></li>
								<li><a href="{% url 'newsfeed:news-list' %}"><i class="fa fa-google-plus"></i></a></li>
								<li><a href="{% url 'newsfeed:news-list' %}"><i class="fa fa-pinterest"></i></a></li>
							</ul>
						</div>
					</div>

				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</footer>
		<!-- /Footer -->

		<!-- jQuery Plugins -->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>
        </body>
</html>

templates/mobile/main_page.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% load news_extras %}

{% block content %}
    		<!-- section -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<!-- post -->
					<div class="col-md-6">
						<div class="post post-thumb">
							<a class="post-img" href="#"><img src="{% static './img/post-1.jpg' %}" alt=""></a>
							<div class="post-body">
								<div class="post-meta">
									<a class="post-category cat-2" href="#">Category</a>
									<span class="post-date">Date</span>
								</div>
								<h3 class="post-title"><a href="#">Title</a></h3>
							</div>
						</div>
					</div>
					<!-- /post -->

					<!-- post -->
					<div class="col-md-6">
						<div class="post post-thumb">
							<a class="post-img" href="#"><img src="{% static './img/post-1.jpg' %}" alt=""></a>
							<div class="post-body">
								<div class="post-meta">
									<a class="post-category cat-3" href="#">Category</a>
									<span class="post-date">Date</span>
								</div>
								<h3 class="post-title"><a href="#">Title</a></h3>
							</div>
						</div>
					</div>
					<!-- /post -->
				</div>
				<!-- /row -->


				{% load_news 6 %}


				<!-- row -->
				<div class="row">
					<div class="col-md-8">
						<div class="row">
							<!-- post -->
							<div class="col-md-12">
								<div class="post post-thumb">
									<a class="post-img" href="#"><img src="{% static './img/post-1.jpg' %}" alt=""></a>
									<div class="post-body">
										<div class="post-meta">
											<a class="post-category cat-3" href="#">Category</a>
											<span class="post-date">Date</span>
										</div>
										<h3 class="post-title"><a href="#">Title</a></h3>
									</div>
								</div>
							</div>
							<!-- /post -->

							<!-- post -->
							<div class="col-md-6">
								<div class="post">
									<a class="post-img" href="#"><img src="{% static './img/post-1.jpg' %}" alt=""></a>
									<div class="post-body">
										<div class="post-meta">
											<a class="post-category cat-4" href="#">Category</a>
											<span class="post-date">Date</span>
										</div>
										<h3 class="post-title"><a href="#">Title</a></h3>
									</div>
								</div>
							</div>
							<!-- /post -->

							<!-- post -->
							<div class="col-md-6">
								<div class="post">
									<a class="post-img" href="#"><img src="{% static './img/post-1.jpg' %}" alt=""></a>
									<div class="post-body">
										<div class="post-meta">
											<a class="post-category cat-1" href="#">Category</a>
											<span class="post-date">Date</span>
										</div>
										<h3 class="post-title"><a href="#">Title</a></h3>
									</div>
								</div>
							</div>
							<!-- /post -->

							<div class="clearfix visible-md visible-lg"></div>

							<!-- post -->
							<div class="col-md-6">
								<div class="post">
									<a class="post-img" href="#"><img src="{% static './img/post-1.jpg' %}" alt=""></a>
									<div class="post-body">
										<div class="post-meta">
											<a class="post-category cat-2" href="#">Category</a>
											<span class="post-date">Date</span>
										</div>
										<h3 class="post-title"><a href="#">Title</a></h3>
									</div>
								</div>
							</div>
							<!-- /post -->

							<!-- post -->
							<div class="col-md-6">
								<div class="post">
									<a class="post-img" href="#"><img src="{% static './img/post-1.jpg' %}" alt=""></a>
									<div class="post-body">
										<div class="post-meta">
											<a class="post-category cat-3" href="#">Category</a>
											<span class="post-date">Date</span>
										</div>
										<h3 class="post-title"><a href="#">Title</a></h3>
									</div>
								</div>
							</div>
							<!-- /post -->

							<div class="clearfix visible-md visible-lg"></div>

							<!-- post -->
							<div class="col-md-6">
								<div class="post">
									<a class="post-img" href="#"><img src="{% static './img/post-1.jpg' %}" alt=""></a>
									<div class="post-body">
										<div class="post-meta">
											<a class="post-category cat-1" href="#">Category</a>
											<span class="post-date">Date</span>
										</div>
										<h3 class="post-title"><a href="#">Title</a></h3>
									</div>
								</div>
							</div>
							<!-- /post -->

							<!-- post -->
							<div class="col-md-6">
								<div class="post">
									<a class="post-img" href="#"><img src="{% static './img/post-1.jpg' %}" alt=""></a>
									<div class="post-body">
										<div class="post-meta">
											<a class="post-category cat-2" href="#">Category</a>
											<span class="post-date">Date</span>
										</div>
										<h3 class="post-title"><a href="#">Title</a></h3>
									</div>
								</div>
							</div>
							<!-- /post -->
						</div>
					</div>

					<div class="col-md-4">
						<!-- post widget -->
						<div class="aside-widget">
							<div class="section-title">
								<h2>Most Read</h2>
							</div>

							<div class="post post-widget">
								<a class="post-img" href="#"><img src="{% static './img/widget-2.jpg' %}" alt=""></a>
								<div class="post-body">
									<h3 class="post-title"><a href="#">Title</a></h3>
								</div>
							</div>

							<div class="post post-widget">
								<a class="post-img" href="#"><img src="{% static './img/widget-2.jpg' %}" alt=""></a>
								<div class="post-body">
									<h3 class="post-title"><a href="#">Title</a></h3>
								</div>
							</div>

							<div class="post post-widget">
								<a class="post-img" href="#"><img src="{% static './img/widget-2.jpg' %}" alt=""></a>
								<div class="post-body">
									<h3 class="post-title"><a href="#">Title</a></h3>
								</div>
							</div>

							<div class="post post-widget">
								<a class="post-img" href="#"><img src="{% static './img/widget-2.jpg' %}" alt=""></a>
								<div class="post-body">
									<h3 class="post-title"><a href="#">Title</a></h3>
								</div>
							</div>
						</div>
						<!-- /post widget -->

						<!-- post widget -->
						<div class="aside-widget">
							<div class="section-title">
								<h2>Featured Posts</h2>
							</div>
							<div class="post post-thumb">
								<a class="post-img" href="#"><img src="{% static './img/post-1.jpg' %}" alt=""></a>
								<div class="post-body">
									<div class="post-meta">
										<a class="post-category cat-3" href="#">Category</a>
										<span class="post-date">Date</span>
									</div>
									<h3 class="post-title"><a href="#">Title</a></h3>
								</div>
							</div>

							<div class="post post-thumb">
								<a class="post-img" href="#"><img src="{% static './img/post-1.jpg' %}" alt=""></a>
								<div class="post-body">
									<div class="post-meta">
										<a class="post-category cat-2" href="#">Category</a>
										<span class="post-date">Date</span>
									</div>
									<h3 class="post-title"><a href="#">Title</a></h3>
								</div>
							</div>
						</div>
						<!-- /post widget -->

						<!-- ad -->
						<div class="aside-widget text-center">
							<a href="#" style="display: inline-block;margin: auto;">
								<img class="img-responsive" src="{% static './img/ad-1.jpg' %}" alt="">
							</a>
						</div>
						<!-- /ad -->
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /section -->

		<!-- section -->
		<div class="section section-grey">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<div class="section-title text-center">
							<h2>Featured Posts</h2>
						</div>
					</div>

					<!-- post -->
					<div class="col-md-4">
						<div class="post">
							<a class="post-img" href="#"><img src="{% static './img/post-1.jpg' %}" alt=""></a>
							<div class="post-body">
								<div class="post-meta">
									<a class="post-category cat-2" href="#">Category</a>
									<span class="post-date">Date</span>
								</div>
								<h3 class="post-title"><a href="#">Title</a></h3>
							</div>
						</div>
					</div>
					<!-- /post -->

					<!-- post -->
					<div class="col-md-4">
						<div class="post">
							<a class="post-img" href="#"><img src="{% static './img/post-1.jpg' %}" alt=""></a>
							<div class="post-body">
								<div class="post-meta">
									<a class="post-category cat-3" href="#">Category</a>
									<span class="post-date">Date</span>
								</div>
								<h3 class="post-title"><a href="#">Title</a></h3>
							</div>
						</div>
					</div>
					<!-- /post -->

					<!-- post -->
					<div class="col-md-4">
						<div class="post">
							<a class="post-img" href="#"><img src="{% static './img/post-1.jpg' %}" alt=""></a>
							<div class="post-body">
								<div class="post-meta">
									<a class="post-category cat-1" href="#">Category</a>
									<span class="post-date">Date</span>
								</div>
								<h3 class="post-title"><a href="#">Title</a></h3>
							</div>
						</div>
					</div>
					<!-- /post -->
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /section -->

		<!-- section -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-8">
						<div class="row">
							<div class="col-md-12">
								<div class="section-title">
									<h2>Most Read</h2>
								</div>
							</div>
							<!-- post -->
							<div class="col-md-12">
								<div class="post post-row">
									<a class="post-img" href="#"><img src="{% static './img/post-1.jpg' %}" alt=""></a>
									<div class="post-body">
										<div class="post-meta">
											<a class="post-category cat-2" href="#">Category</a>
											<span class="post-date">Date</span>
										</div>
										<h3 class="post-title"><a href="#">Title</a></h3>
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam...</p>
									</div>
								</div>
							</div>
							<!-- /post -->

							<!-- post -->
							<div class="col-md-12">
								<div class="post post-row">
									<a class="post-img" href="#"><img src="{% static './img/post-1.jpg' %}" alt=""></a>
									<div class="post-body">
										<div class="post-meta">
											<a class="post-category cat-2" href="#">Category</a>
											<span class="post-date">Date</span>
										</div>
										<h3 class="post-title"><a href="#">Title</a></h3>
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam...</p>
									</div>
								</div>
							</div>
							<!-- /post -->

							<!-- post -->
							<div class="col-md-12">
								<div class="post post-row">
									<a class="post-img" href="#"><img src="{% static './img/post-1.jpg' %}" alt=""></a>
									<div class="post-body">
										<div class="post-meta">
											<a class="post-category cat-4" href="#">Category</a>
											<span class="post-date">Date</span>
										</div>
										<h3 class="post-title"><a href="#">Title</a></h3>
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam...</p>
									</div>
								</div>
							</div>
							<!-- /post -->

							<!-- post -->
							<div class="col-md-12">
								<div class="post post-row">
									<a class="post-img" href="#"><img src="{% static './img/post-1.jpg' %}" alt=""></a>
									<div class="post-body">
										<div class="post-meta">
											<a class="post-category cat-3" href="#">Category</a>
											<span class="post-date">Date</span>
										</div>
										<h3 class="post-title"><a href="#">Title</a></h3>
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam...</p>
									</div>
								</div>
							</div>
							<!-- /post -->

							<div class="col-md-12">
								<div class="section-row">
									<button class="primary-button center-block">Load More</button>
								</div>
							</div>
						</div>
					</div>

					<div class="col-md-4">
						<!-- ad -->
						<div class="aside-widget text-center">
							<a href="#" style="display: inline-block;margin: auto;">
								<img class="img-responsive" src="{% static './img/ad-1.jpg' %}" alt="">
							</a>
						</div>
						<!-- /ad -->

						<!-- catagories -->
						<div class="aside-widget">
							<div class="section-title">
								<h2>Catagories</h2>
							</div>
							<div class="category-widget">
								<ul>
									<li><a href="#" class="cat-1">Web Design<span>340</span></a></li>
									<li><a href="#" class="cat-2">JavaScript<span>74</span></a></li>
									<li><a href="#" class="cat-4">JQuery<span>41</span></a></li>
									<li><a href="#" class="cat-3">CSS<span>35</span></a></li>
								</ul>
							</div>
						</div>
						<!-- /catagories -->

						<!-- tags -->
						<div class="aside-widget">
							<div class="tags-widget">
								<ul>
									<li><a href="#">Chrome</a></li>
									<li><a href="#">CSS</a></li>
									<li><a href="#">Tutorial</a></li>
									<li><a href="#">Backend</a></li>
									<li><a href="#">JQuery</a></li>
									<li><a href="#">Design</a></li>
									<li><a href="#">Development</a></li>
									<li><a href="#">JavaScript</a></li>
									<li><a href="#">Website</a></li>
								</ul>
							</div>
						</div>
						<!-- /tags -->
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /section -->



{% endblock %}

templates/mobile/signup.html
{% extends 'base.html' %}

{% block content %}

    <h2>Регистрация</h2>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button  class="btn btn-primary" type="submit">Регистрация</button>
    </form>

{% endblock content %}