mkdev_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.flatpages import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap, NewsSitemap, ArticlesSitemap
from newsfeed.urls import *
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from rest_framework.routers import DefaultRouter
from newsfeed import views


sitemaps = {
    'static': StaticViewSitemap,
    'flatpages': FlatPageSitemap,
    'news': NewsSitemap,
    'articles': ArticlesSitemap,
}

router = DefaultRouter()
router.register('api/newsfeed', views.NewsViewSet)
router.register('api/articles', views.ArticlesViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('newsfeed.urls', namespace='newsfeed')),
    path('', TemplateView.as_view(template_name="main_page.html")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('', include(router.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

urlpatterns += path('', include('django.contrib.flatpages.urls')),  # в конце, потому что любит перехватывать ссылки

newsfeed/urls.py
from django.urls import path, re_path
from newsfeed.views import *

app_name = 'newsfeed'

urlpatterns = [
    path(r'newsfeed/<slug:slug>/', NewsPostDetailView.as_view(), name='news-detail'),
    path(r'newsfeed/', NewsPostListView.as_view(), name='news-list'),
    path(r'articles/<slug:slug>/', ArticleDetailView.as_view(), name='article-detail'),
    path(r'articles/', ArticleListView.as_view(), name='article-list'),
    path(r'search/', SearchListView.as_view(), name='search'),
    path(r'archive/', zip_archive, name='archive-csv'),
]

newsfeed/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.core.mail import send_mail
from django.contrib.auth.models import Group
from accounts.models import CustomUser
from .utils import get_unique_slug
from ckeditor.fields import RichTextField
from django.urls import reverse
from django.contrib.sitemaps import ping_google
from meta.models import ModelMeta


STATUS_CHOICES = [
    ('d', 'Draft'),
    ('p', 'Published'),
    ('w', 'Withdrawn'),
]


class NewsPost(ModelMeta, models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    category = models.ForeignKey(
        'Category',
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    image = models.ImageField(
        upload_to='uploads',
        height_field=None,
        width_field=None,
        max_length=100,
        default='default.jpg'
    )
    text = models.TextField(max_length=200)
    slug = models.SlugField(max_length=300, default='', unique=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='d')
    _metadata = {
        'keywords': 'title',
        'description': 'title',
        'image': 'get_meta_image',
    }

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, 'title', 'slug')
        super().save(*args, **kwargs)
        ping_google()

    # def get_absolute_url(self):
    #     return reverse('news-detail', args=[str(self.slug)])

    def get_absolute_url(self):
        return "/newsfeed/%i/" % self.id

    def get_meta_image(self):
        if self.image:
            return self.image.url


class Category(models.Model):
    title = models.CharField(max_length=100)


class Article(ModelMeta, models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    tags = models.ManyToManyField(
        'Tag',
        related_name="tags",
        blank=True,
    )
    image = models.ImageField(
        upload_to='uploads',
        height_field=None,
        width_field=None,
        max_length=100,
        default='default.jpg')
    content = RichTextField(default='')
    slug = models.SlugField(max_length=300, default='', unique=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='d')
    _metadata = {
        'keywords': 'title',
        'description': 'title',
        'image': 'get_meta_image',
    }

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, 'title', 'slug')
        super().save(*args, **kwargs)
        ping_google()

    # def get_absolute_url(self):
    #     return reverse('article-detail', args=[str(self.slug)])

    def get_absolute_url(self):
        return "/articles/%i/" % self.id

    def get_meta_image(self):
        if self.image:
            return self.image.url


class Tag(models.Model):
    title = models.CharField(max_length=100)


@receiver(post_save, sender=NewsPost)
def send_notifications(sender, instance, *args, **kwargs):
    if instance.published_date:
        group = Group.objects.get(name='mailing_group')
        send_mail('Опубликована новость на сайте',
                  'Зайдите на сайт - там опубликована новость',
                  'web-django-test@yandex.ru',
                  group.user_set.values_list('email', flat=True), fail_silently=False)

newsfeed/views.py
from django.shortcuts import render
from django.utils import timezone
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from newsfeed.models import NewsPost, Article
from django.contrib.postgres.search import SearchVector, SearchQuery
from itertools import chain
import csv
from django.http import HttpResponse
import zipfile
import os
from io import BytesIO
from rest_framework.response import Response
from rest_framework import viewsets
from rest_framework import serializers
from django_filters.rest_framework import DjangoFilterBackend


class NewsPostDetailView(DetailView):

    model = NewsPost

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        context['meta'] = self.get_object().as_meta(self.request)
        return context


class NewsPostListView(ListView):

    model = NewsPost
    queryset = NewsPost.objects.filter(published_date__isnull=False)
    template_name = 'newsfeed/newspost_list.html'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        news_posts = NewsPost.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
        if request.mobile:
            return render(request, 'mobile/newsfeed/newspost_list.html', {'news_list': news_posts})
        else:
            return render(request, 'newsfeed/newspost_list.html', {'news_list': news_posts})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

    def get_queryset(self):
        news_queryset = super().get_queryset()
        d = self.request.GET.copy()
        d.pop('page', 'default_key')
        return news_queryset.filter(**d)


class ArticleDetailView(DetailView):

    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        context['meta'] = self.get_object().as_meta(self.request)
        return context


class ArticleListView(ListView):

    model = Article
    queryset = Article.objects.filter(published_date__isnull=False)
    template_name = 'newsfeed/article_list.html'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        articles = Article.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
        if request.mobile:
            return render(request, 'mobile/newsfeed/article_list.html', {'article_list': articles})
        else:
            return render(request, 'newsfeed/article_list.html', {'article_list': articles})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

    def get_queryset(self):
        articles_queryset = super().get_queryset()
        d = self.request.GET.copy()
        d.pop('page', 'default_key')
        return articles_queryset.filter(**d)


class SearchListView(ListView):
    model = NewsPost, Article
    paginate_by = 10
    template_name = 'newsfeed/search_list.html'

    def get(self, request, *args, **kwargs):
        search_list = self.get_queryset()
        if request.mobile:
            return render(request, 'mobile/newsfeed/search_list.html', {'search_list': search_list})
        else:
            return render(request, 'newsfeed/search_list.html', {'search_list': search_list})

    def get_queryset(self):
        queryset_news = NewsPost.objects.filter(published_date__isnull=False)
        queryset_articles = Article.objects.filter(published_date__isnull=False)

        keywords = self.request.GET.get('q')
        query = SearchQuery(keywords)
        news_title_vector = SearchVector('title', weight='A')
        news_content_vector = SearchVector('text', weight='B')
        news_vectors = news_title_vector + news_content_vector
        queryset_news = queryset_news.annotate(search=news_vectors).filter(search=query)

        article_title_vector = SearchVector('title', weight='A')
        article_content_vector = SearchVector('content', weight='B')
        article_vectors = article_title_vector + article_content_vector
        queryset_articles = queryset_articles.annotate(search=article_vectors).filter(search=query)

        return list(chain(queryset_articles, queryset_news))


def article_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="articles.csv"'
    articles = Article.objects.filter(published_date__isnull=False)
    writer = csv.writer(response)
    for article in articles:
        writer.writerow([article.title, article.content, article.created_date])
    return response


def news_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="newsfeed.csv"'
    news_list = NewsPost.objects.filter(published_date__isnull=False)
    writer = csv.writer(response)
    for news in news_list:
        writer.writerow([news.title, news.text, news.created_date])
    return response


def zip_archive(request):
    with open('articles.csv', 'w', newline='') as article_file:
        article_fields = ['Title', 'Text', 'Created date']
        articles = Article.objects.filter(published_date__isnull=False)
        article_writer = csv.DictWriter(article_file, fieldnames=article_fields, delimiter=';')
        article_writer.writeheader()
        for article in articles:
            article_writer.writerow({
                'Title': article.title,
                'Text': article.content,
                'Created date': article.created_date
            })

    with open('newsfeed.csv', 'w', newline='') as news_file:
        news_fields = ['Title', 'Text', 'Created date']
        news_list = NewsPost.objects.filter(published_date__isnull=False)
        news_writer = csv.DictWriter(news_file, fieldnames=news_fields, delimiter=';')
        news_writer.writeheader()
        for news in news_list:
            news_writer.writerow({
                'Title': news.title,
                'Text': news.text,
                'Created date': news.created_date
            })

    buffer = BytesIO()
    with zipfile.ZipFile(buffer, 'w') as archive:
        archive.write('articles.csv')
        archive.write('newsfeed.csv')

    os.remove('articles.csv')
    os.remove('newsfeed.csv')

    response = HttpResponse(buffer.getvalue())
    response['Content-Type'] = 'application/x-zip-compressed'
    response['Content-Disposition'] = 'attachment; filename=archive.zip'
    return response


class NewsListSerializer(serializers.HyperlinkedModelSerializer):
    url = serializers.HyperlinkedIdentityField(view_name='newspost-detail', read_only=True)
    author = serializers.StringRelatedField(many=False)

    class Meta:
        model = NewsPost
        fields = ['id', 'author', 'title', 'text', 'image', 'url']


class NewsViewSet(viewsets.ModelViewSet):
    queryset = NewsPost.objects.filter(published_date__isnull=False)
    serializer_class = NewsListSerializer
    filter_backends = [DjangoFilterBackend]
    filter_fields = ['category__title', 'author__username']

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.get_serializer(instance)
        return Response(serializer.data)


class ArticleListSerializer(serializers.HyperlinkedModelSerializer):
    url = serializers.HyperlinkedIdentityField(view_name='article-detail', read_only=True)
    author = serializers.StringRelatedField(many=False)

    class Meta:
        model = Article
        fields = ['id', 'author', 'title', 'content', 'image', 'url']


class ArticlesViewSet(viewsets.ModelViewSet):
    queryset = Article.objects.filter(published_date__isnull=False)
    serializer_class = ArticleListSerializer
    filter_backends = [DjangoFilterBackend]
    filter_fields = ['tags__title', 'author__username']

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.get_serializer(instance)
        return Response(serializer.data)


# class CategoryListView(ListView):
#
#     model = NewsPost
#     paginate_by = 100
#     queryset = NewsPost.objects.filter(published_date__isnull=False)
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['now'] = timezone.now()
#         return context
#
#     def news_list(request):
#         news_posts = NewsPost.objects.filter(category_title='javascript')
#         return render(request, 'post_list.html', {'news_posts': news_posts})

templates/mobile/newsfeed/article_detail.html
{% extends 'base.html' %}

{% block content %}

    <div id="post-header" class="page-header">
				<div class="background-img" style="background-image: url({{ article.image.url }});"></div>
				<div class="container">
					<div class="row">
						<div class="col-md-10">
							<div class="post-meta">
								<a class="post-category cat-2" href="#">{{ article.tags.title }}</a>
								<span class="post-date">{{ article.created_date }}</span>
							</div>
							<h1>{{ article.title }}</h1>
						</div>
					</div>
				</div>
			</div>


    <div class="col-md-8">
						<div class="section-row sticky-container">
							<div class="main-post">
								<h3>{{ article.title }}</h3>
								{{ article.content|safe }}

                            <p></p>
                            <p>Tags:
                                    {% for tag in article.tags.all %}
                                <a href="?tags__title__in={{ tag.title }}">{{ tag.title }}</a>
                                {% endfor %}
                            </p>
                            </div></div></div>

{% endblock %}

templates/mobile/newsfeed/article_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}
    <h1>Articles</h1>
    <ul>
    {% for article in article_list %}
        {% thumbnail article.image "300x300" as im %}
                <a href="#"><img src="{{ im.url }}" alt=""></a>
                {% endthumbnail %}
                        <a href="?tags__title__in={{ article.tags }}">{{ article.tags }}</a>
                        <span>{{ article.created_date }}</span>

                    <h3><a href="{% url 'newsfeed:article-detail' article.slug %}">{{ article.title }}</a></h3>
                    <p>{{ article.content|safe }}</p>

                    <p> Tags:
                    {% for tag in article.tags.all %}
                    <a href="?tags__title__in={{ tag.title }}">{{ tag.title }}</a>
                    {% endfor %}
                    </p>

    {% empty %}
        <li>No articles yet.</li>
    {% endfor %}
    </ul>

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}

templates/mobile/newsfeed/featured_news_block.html
					<div class="col-md-4">

						<div class="aside-widget">
							<div class="section-title">
								<h2>Featured Posts</h2>
							</div>

  {% for object in object_list %}

                            	<div class="post post-thumb">
								<a class="post-img" href="{% url 'newsfeed:news-detail' object.slug %}"><img src="{{ object.image.url }}" alt=""></a>
								<div class="post-body">
									<div class="post-meta">
										<a class="post-category cat-3" href="{% url 'newsfeed:news-list' %}?category__title__in={{ object.category.title }}">{{ object.category.title }}</a>
										<span class="post-date">{{ object.created_date }}</span>
									</div>
									<h3 class="post-title"><a href="{% url 'newsfeed:news-detail' object.slug %}">{{ object.title }}</a></h3>
								</div>
							</div>
  {% endfor %}


                            </div>
					</div>

templates/mobile/newsfeed/news_block.html
                    <div class="row">
					<div class="col-md-12">
						<div class="section-title">
							<h2>Recent Posts</h2>
						</div>
					</div>

                        {% for object in object_list %}

    					<div class="col-md-4">
						<div class="post">
							<a class="post-img" href="{% url 'newsfeed:news-detail' object.slug %}"><img src="{{ object.image.url }}" alt=""></a>
							<div class="post-body">
								<div class="post-meta">
									<a class="post-category cat-1" href="{% url 'newsfeed:news-list' %}?category__title__in={{ object.category.title }}">{{ object.category.title }}</a>
									<span class="post-date">{{ object.created_date }}</span>
								</div>
								<h3 class="post-title"><a href="{% url 'newsfeed:news-detail' object.slug %}">{{ object.title }}</a></h3>
							</div>
						</div>
					</div>

                        {% endfor %}

templates/mobile/newsfeed/newspost_detail.html
{% extends 'base.html' %}
{% load news_extras %}

{% block content %}

    <div id="post-header" class="page-header">
				<div class="background-img" style="background-image: url({{ newspost.image.url }});"></div>
				<div class="container">
					<div class="row">
						<div class="col-md-10">
							<div class="post-meta">
								<a class="post-category cat-2" href="#">{{ newspost.category.title }}</a>
								<span class="post-date">{{ newspost.created_date }}</span>
							</div>
							<h1>{{ newspost.title }}</h1>
						</div>
					</div>
				</div>
			</div>


    <div class="col-md-8">
						<div class="section-row sticky-container">
							<div class="main-post">
								<h3>{{ newspost.title }}</h3>
								{{ newspost.text }}
                                </div></div></div>

{% load_featured_news newspost.category_id %}

{% endblock %}

templates/mobile/newsfeed/newspost_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}
    <h1>News Posts</h1>
    <ul>
    {% for newspost in news_list %}
               {% thumbnail newspost.image "300x300" as im %}
                <a href="#"><img src="{{ im.url }}" alt=""></a>
                {% endthumbnail %}
        <a href="?category__title__in={{ newspost.category.title }}">{{ newspost.category.title }}</a>
                        <span>{{ newspost.created_date }}</span>
                    <h3><a href="{% url 'newsfeed:news-detail' newspost.slug %}">{{ newspost.title }}</a></h3>
                    <p>{{ newspost.text }}</p>

    {% empty %}
        <li>No news posts yet.</li>
    {% endfor %}
    </ul>

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}

templates/mobile/newsfeed/search_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Search results</h1>
    <ul>
        {% for object in search_list %}

                <a href="#"><img src="{{ object.image }}" alt=""></a>
                        <span>{{ object.created_date }}</span>

                    <h3><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h3>
                    <p>{{ object.content|safe }}</p>
                    <p>{{ object.text }}</p>

  {% endfor %}
</ul>

{% endblock %}